sonar.projectKey=fintech_pipeline
sonar.projectName=fintech_pipeline
sonar.sourceEncoding=UTF-8
sonar.python.version=3.14

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

sonar.exclusions=\
  **/__pycache__/**,\
  **/*.pyc,\
  venv/**,\
  .venv/**,\
  env/**,\
  data/**,\
  logs/**,\
  outputs/**,\
  notebooks/**,\
  Material/**,\
  htmlcov/**,\
  .pytest_cache/**,\
  .pytest_tmp/**

sonar.coverage.exclusions=\
  tests/**,\
  src/agent/app.py,\
  src/agent/run_agent.py,\
  src/agent/streamlit_app.py

sonar.python.coverage.reportPaths=coverage.xml
